### ISSUE TITLE
Jump to letters not working as expected

### ISSUE THREAD

**Issue by PlexMovieFan** [plexinc/WebClient.bundle#53]
[All types] When a list is in reverse alphabetical order, jump to not available?
[music] Switching from Artist Type to Album or Track Type, then back to Artist Type, it disappears.  But there is space for it.  Almost like it is not refreshing that part of the screen.
[music] With Album or Track Type, default sort is by artist.  No jump letters, although there is space for it.  If you change the sort to reverse then back, then change the type to Album or Track, the letters show up.  But the jump to does not work correctly.  If I click on say the letter "H".  It jumps to some random artist and random track, that does not appear to line up with "H" in any way.

When the sort order is by name it works as expected.  The jump letters appear to be the same list as when they show up using artist sort as I mentioned above.  So the jump letters showing above might be wrong and should not show up when using artist sort.

**Comment by ericmatthys** [comment]
Tracking this internally now. It should be fixed today or tomorrow.

**Comment by PlexMovieFan** [comment]
I see the changes, but still not quite right.  When changing views initially to Album (sort by Artist), the letters are there, but If I change the sort order from asc to desc and back, they are gone.  I'm guessing the initial screen should not be there as this list is picking up the first letter of the albums, which makes no sense as it is sorted by artist.

Still would like to see the list when in reverse order too.

**Comment by ericmatthys** [comment]
Reverse order won't be supported at this time, but the bug should be fixed in the next update.
